export const MASCOTS = [
  { coin: "Bitcoin", symbol: "BTC", title: "The Viking King", role: "Guardian of digital scarcity", image: "/mascots/bitcoin-viking-king-v2.webp", accent: "from-amber-400/35 via-orange-500/10 to-transparent", border: "hover:border-amber-400/60", lore: "Forged in discipline and protected by a golden shield, the Viking King represents resilience, sovereignty and Bitcoin's fixed supply.", quote: "Gold fades. Blocks remain." },
  { coin: "Ethereum", symbol: "ETH", title: "The Sovereign", role: "Architect of programmable worlds", image: "/mascots/ethereum-sovereign.webp", accent: "from-violet-400/30 via-indigo-500/10 to-transparent", border: "hover:border-violet-400/60", lore: "The Sovereign commands a crystalline city where code becomes infrastructure, embodying Ethereum's role as a foundation for decentralized applications.", quote: "Code is the architecture of new worlds." },
  { coin: "XRP", symbol: "XRP", title: "The Velocity Guardian", role: "Sentinel of global value transfer", image: "/mascots/xrp-velocity-guardian.webp", accent: "from-slate-200/25 via-sky-400/10 to-transparent", border: "hover:border-sky-300/60", lore: "Built for precision and speed, the Velocity Guardian watches over luminous routes connecting markets and communities across the world.", quote: "Distance is only a problem for the slow." },
  { coin: "Solana", symbol: "SOL", title: "The Neon Ronin", role: "Warrior of parallel execution", image: "/mascots/solana-neon-ronin.webp", accent: "from-cyan-400/25 via-fuchsia-500/15 to-transparent", border: "hover:border-fuchsia-400/60", lore: "The Neon Ronin moves through a rain-lit city with disciplined speed, reflecting Solana's high-throughput design and ambitious ecosystem.", quote: "Move with speed. Execute with purpose." },
  { coin: "BNB", symbol: "BNB", title: "The Golden Architect", role: "Builder of a vast ecosystem", image: "/mascots/bnb-golden-architect.webp", accent: "from-yellow-400/30 via-amber-500/10 to-transparent", border: "hover:border-yellow-400/60", lore: "The Golden Architect unites infrastructure, utility and scale inside a monumental black-and-gold citadel.", quote: "Build the system. Expand the horizon." },
  { coin: "Dogecoin", symbol: "DOGE", title: "The Lunar Captain", role: "Explorer powered by community", image: "/mascots/dogecoin-lunar-captain.webp", accent: "from-amber-300/25 via-yellow-600/10 to-transparent", border: "hover:border-amber-300/60", lore: "Optimistic, loyal and ready for the next mission, the Lunar Captain celebrates the culture and community energy behind Dogecoin.", quote: "The mission is better with the whole crew." },
  { coin: "Cardano", symbol: "ADA", title: "The Celestial Scholar", role: "Strategist of rigorous systems", image: "/mascots/cardano-celestial-scholar.webp", accent: "from-blue-400/25 via-cyan-500/10 to-transparent", border: "hover:border-blue-400/60", lore: "Guided by research and a constellation of carefully arranged nodes, the Celestial Scholar represents methodical engineering and long-term vision.", quote: "Measure twice. Build for generations." },
  { coin: "Chainlink", symbol: "LINK", title: "The Oracle Sentinel", role: "Guardian of verifiable data", image: "/mascots/chainlink-oracle-sentinel.webp", accent: "from-blue-500/25 via-sky-400/10 to-transparent", border: "hover:border-blue-500/60", lore: "Standing between digital kingdoms and the real world, the Oracle Sentinel protects the secure bridges that carry trusted information.", quote: "Truth must cross every border intact." },
  { coin: "Avalanche", symbol: "AVAX", title: "The Crimson Mountaineer", role: "Champion of rapid finality", image: "/mascots/avalanche-crimson-mountaineer.webp", accent: "from-red-500/30 via-rose-500/10 to-transparent", border: "hover:border-red-400/60", lore: "The Crimson Mountaineer holds the summit through speed, resilience and decisive finality across a landscape of connected networks.", quote: "Reach the summit. Finalize the path." },
  { coin: "Polkadot", symbol: "DOT", title: "The Multiverse Conductor", role: "Commander of connected worlds", image: "/mascots/polkadot-multiverse-conductor.webp", accent: "from-pink-500/30 via-fuchsia-500/10 to-transparent", border: "hover:border-pink-400/60", lore: "With many sovereign worlds moving in harmony, the Multiverse Conductor symbolizes interoperability and shared security.", quote: "Many worlds. One coordinated future." },
  { coin: "Shiba Inu", symbol: "SHIB", title: "The Ember Shogun", role: "Guardian of the community flame", image: "/mascots/shib-ember-shogun.webp", accent: "from-orange-400/30 via-red-500/10 to-transparent", border: "hover:border-orange-400/60", lore: "A disciplined guardian whose strength comes from a vast community moving with a shared purpose.", quote: "A million sparks can light one horizon." },
  { coin: "Pepe", symbol: "PEPE", title: "The Meme Alchemist", role: "Alchemist of internet culture", image: "/mascots/pepe-meme-alchemist.webp", accent: "from-lime-400/25 via-emerald-500/10 to-transparent", border: "hover:border-lime-400/60", lore: "A quick-witted alchemist shaped by the speed, humor and unpredictability of internet culture.", quote: "Culture moves before the map is drawn." },
  { coin: "Hyperliquid", symbol: "HYPE", title: "The Perpetual Warden", role: "Warden of high-speed markets", image: "/mascots/hype-perpetual-warden.webp", accent: "from-emerald-300/25 via-cyan-500/10 to-transparent", border: "hover:border-emerald-300/60", lore: "A vigilant warden built for transparent, always-on markets and decisive execution.", quote: "Stay liquid. Stay ready." },
  { coin: "TRON", symbol: "TRX", title: "The Solar Regent", role: "Regent of global digital rails", image: "/mascots/trx-solar-regent.webp", accent: "from-red-400/30 via-orange-500/10 to-transparent", border: "hover:border-red-400/60", lore: "A radiant regent coordinating efficient digital routes across a far-reaching network.", quote: "Build the rails. Open the world." },
  { coin: "Sui", symbol: "SUI", title: "The Tidal Blade", role: "Warrior of fluid execution", image: "/mascots/sui-tidal-blade.webp", accent: "from-cyan-300/25 via-blue-500/10 to-transparent", border: "hover:border-cyan-300/60", lore: "A fast-moving warrior shaped by water, precision and object-centered design.", quote: "Flow around limits. Strike with clarity." },
] as const;

export const CHALLENGER_MASCOTS = [
  { coin: "Toncoin", symbol: "TON", title: "The Network Voyager", role: "Explorer of open networks", image: "", accent: "from-sky-400/25 via-blue-500/10 to-transparent", border: "hover:border-sky-400/60", lore: "A challenger navigating fast, connected digital territories with calm precision.", quote: "Every network opens a new horizon." },
  { coin: "Polygon", symbol: "MATIC", title: "The Purple Pathfinder", role: "Guide across scaling frontiers", image: "", accent: "from-violet-400/25 via-purple-500/10 to-transparent", border: "hover:border-violet-400/60", lore: "A pathfinder built for the routes that connect applications, users and scalable execution.", quote: "The shortest path is the one we build." },
  { coin: "Cosmos", symbol: "ATOM", title: "The Cosmos Navigator", role: "Navigator of sovereign chains", image: "", accent: "from-indigo-400/25 via-slate-500/10 to-transparent", border: "hover:border-indigo-400/60", lore: "A navigator charting safe passage between independent blockchain worlds.", quote: "Sovereign worlds can still travel together." },
  { coin: "NEAR Protocol", symbol: "NEAR", title: "The Horizon Keeper", role: "Keeper of accessible systems", image: "", accent: "from-emerald-400/25 via-teal-500/10 to-transparent", border: "hover:border-emerald-400/60", lore: "A patient guardian watching the horizon for technology people can actually use.", quote: "The future belongs within reach." },
  { coin: "Aptos", symbol: "APT", title: "The Parallel Vanguard", role: "Vanguard of parallel systems", image: "", accent: "from-teal-300/25 via-slate-500/10 to-transparent", border: "hover:border-teal-300/60", lore: "A disciplined vanguard coordinating many paths of execution at once.", quote: "Many paths. One decisive advance." },
  { coin: "Arbitrum", symbol: "ARB", title: "The Layer Guardian", role: "Guardian of rollup frontiers", image: "", accent: "from-blue-400/25 via-sky-500/10 to-transparent", border: "hover:border-blue-400/60", lore: "A guardian protecting the bridge between settlement and scalable execution.", quote: "Scale the frontier. Protect the foundation." },
  { coin: "Injective", symbol: "INJ", title: "The Exchange Warden", role: "Warden of open markets", image: "", accent: "from-cyan-400/25 via-indigo-500/10 to-transparent", border: "hover:border-cyan-400/60", lore: "A market warden trained for speed, coordination and open financial rails.", quote: "Open markets demand disciplined guardians." },
  { coin: "Litecoin", symbol: "LTC", title: "The Silver Ranger", role: "Ranger of resilient payments", image: "", accent: "from-slate-300/25 via-blue-500/10 to-transparent", border: "hover:border-slate-300/60", lore: "A veteran ranger carrying a long record of steady, resilient digital settlement.", quote: "Endurance is its own form of speed." },
  { coin: "Uniswap", symbol: "UNI", title: "The Liquidity Alchemist", role: "Alchemist of decentralized exchange", image: "", accent: "from-pink-400/25 via-rose-500/10 to-transparent", border: "hover:border-pink-400/60", lore: "An alchemist balancing pools, routes and open access to decentralized markets.", quote: "Liquidity turns possibility into motion." },
] as const;

export const ALL_MASCOTS = [...MASCOTS, ...CHALLENGER_MASCOTS] as const;
export type Mascot = (typeof ALL_MASCOTS)[number];

export function mascotFor(symbol: string) {
  return ALL_MASCOTS.find((mascot) => mascot.symbol === symbol.toUpperCase());
}
