export const MASCOTS = [
  { coin: "Bitcoin", symbol: "BTC", title: "The Viking King", role: "Guardian of digital scarcity", image: "/mascots/bitcoin-viking-king-v2.webp", accent: "from-amber-400/35 via-orange-500/10 to-transparent", border: "hover:border-amber-400/60", lore: "Forged in discipline and protected by a golden shield, the Viking King represents resilience, sovereignty and Bitcoin's fixed supply.", quote: "Gold fades. Blocks remain." },
  { coin: "Ethereum", symbol: "ETH", title: "The Sovereign", role: "Architect of programmable worlds", image: "/mascots/ethereum-sovereign.webp", accent: "from-violet-400/30 via-indigo-500/10 to-transparent", border: "hover:border-violet-400/60", lore: "The Sovereign commands a crystalline city where code becomes infrastructure, embodying Ethereum's role as a foundation for decentralized applications.", quote: "Code is the architecture of new worlds." },
  { coin: "XRP", symbol: "XRP", title: "The Velocity Guardian", role: "Sentinel of global value transfer", image: "/mascots/xrp-velocity-guardian.webp", accent: "from-slate-200/25 via-sky-400/10 to-transparent", border: "hover:border-sky-300/60", lore: "Built for precision and speed, the Velocity Guardian watches over luminous routes connecting markets and communities across the world.", quote: "Distance is only a problem for the slow." },
  { coin: "Solana", symbol: "SOL", title: "The Neon Ronin", role: "Warrior of parallel execution", image: "/mascots/solana-neon-ronin.webp", accent: "from-cyan-400/25 via-fuchsia-500/15 to-transparent", border: "hover:border-fuchsia-400/60", lore: "The Neon Ronin moves through a rain-lit city with disciplined speed, reflecting Solana's high-throughput design and ambitious ecosystem.", quote: "Move with speed. Execute with purpose." },
  { coin: "BNB", symbol: "BNB", title: "The Golden Architect", role: "Builder of a vast ecosystem", image: "/mascots/bnb-golden-architect.webp", accent: "from-yellow-400/30 via-amber-500/10 to-transparent", border: "hover:border-yellow-400/60", lore: "The Golden Architect unites infrastructure, utility and scale inside a monumental black-and-gold citadel.", quote: "Build the system. Expand the horizon." },
  { coin: "Dogecoin", symbol: "DOGE", title: "The Lunar Captain", role: "Explorer powered by community", image: "/mascots/dogecoin-lunar-captain.webp", accent: "from-amber-300/25 via-yellow-600/10 to-transparent", border: "hover:border-amber-300/60", lore: "Optimistic, loyal and ready for the next mission, the Lunar Captain celebrates the culture and community energy behind Dogecoin.", quote: "The mission is better with the whole crew." },
  { coin: "Cardano", symbol: "ADA", title: "The Celestial Scholar", role: "Strategist of rigorous systems", image: "/mascots/cardano-celestial-scholar.webp", accent: "from-blue-400/25 via-cyan-500/10 to-transparent", border: "hover:border-blue-400/60", lore: "Guided by research and a constellation of carefully arranged nodes, the Celestial Scholar represents methodical engineering and long-term vision.", quote: "Measure twice. Build for generations." },
  { coin: "Chainlink", symbol: "LINK", title: "The Oracle Sentinel", role: "Guardian of verifiable data", image: "/mascots/chainlink-oracle-sentinel.webp", accent: "from-blue-500/25 via-sky-400/10 to-transparent", border: "hover:border-blue-500/60", lore: "Standing between digital kingdoms and the real world, the Oracle Sentinel protects the secure bridges that carry trusted information.", quote: "Truth must cross every border intact." },
  { coin: "Avalanche", symbol: "AVAX", title: "The Crimson Mountaineer", role: "Champion of rapid finality", image: "/mascots/avalanche-crimson-mountaineer.webp", accent: "from-red-500/30 via-rose-500/10 to-transparent", border: "hover:border-red-400/60", lore: "The Crimson Mountaineer holds the summit through speed, resilience and decisive finality across a landscape of connected networks.", quote: "Reach the summit. Finalize the path." },
  { coin: "Polkadot", symbol: "DOT", title: "The Multiverse Conductor", role: "Commander of connected worlds", image: "/mascots/polkadot-multiverse-conductor.webp", accent: "from-pink-500/30 via-fuchsia-500/10 to-transparent", border: "hover:border-pink-400/60", lore: "With many sovereign worlds moving in harmony, the Multiverse Conductor symbolizes interoperability and shared security.", quote: "Many worlds. One coordinated future." },
] as const;

export type Mascot = (typeof MASCOTS)[number];

export function mascotFor(symbol: string) {
  return MASCOTS.find((mascot) => mascot.symbol === symbol.toUpperCase());
}
